title: Global Socket
author: skyper
description: Connect like there is no firewall. Securely.
repository_url: https://github.com/hackerschoice/gsocket
google_analytics:
theme: jekyll-theme-midnight
twitter_username: hackerschoice
github_username:  hackerschoice
social-network-links:
  github: hackerschoice
  twitter: hackerschoice
